// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Colors$ReactHooksTemplate = require("../theme/Colors.bs.js");

var label = Css.style(/* :: */[
      Css.color(/* `hex */[
            5194459,
            Colors$ReactHooksTemplate.primary200
          ]),
      /* :: */[
        Css.display(/* inlineBlock */-147785676),
        /* :: */[
          Css.fontSize(/* `px */[
                25096,
                14
              ]),
          /* :: */[
            Css.fontWeight(/* `num */[
                  5496390,
                  500
                ]),
            /* :: */[
              Css.marginBottom(/* `px */[
                    25096,
                    4
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* label */label];

function FormLabel(Props) {
  var children = Props.children;
  var htmlFor = Props.htmlFor;
  var tmp = {
    className: label
  };
  if (htmlFor !== undefined) {
    tmp.htmlFor = Caml_option.valFromOption(htmlFor);
  }
  return React.createElement("label", tmp, children);
}

var make = FormLabel;

exports.Styles = Styles;
exports.make = make;
/* label Not a pure module */
