// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Colors$ReactHooksTemplate = require("./theme/Colors.bs.js");

var divider = Css.style(/* :: */[
      Css.backgroundColor(/* `hex */[
            5194459,
            Colors$ReactHooksTemplate.primary450
          ]),
      /* :: */[
        Css.height(/* `px */[
              25096,
              1
            ]),
        /* :: */[
          Css.marginBottom(/* `px */[
                25096,
                4
              ]),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* divider */divider];

function Divider(Props) {
  return React.createElement("div", {
              className: divider
            });
}

var make = Divider;

exports.Styles = Styles;
exports.make = make;
/* divider Not a pure module */
