// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Css = require("bs-css/src/Css.js");
var React = require("react");
var Colors$ReactHooksTemplate = require("./theme/Colors.bs.js");

var body = Css.style(/* :: */[
      Css.color(/* `hex */[
            5194459,
            Colors$ReactHooksTemplate.primary100
          ]),
      /* :: */[
        Css.fontSize(/* `px */[
              25096,
              16
            ]),
        /* :: */[
          Css.lineHeight(Css.px(22)),
          /* [] */0
        ]
      ]
    ]);

var header = Css.style(/* :: */[
      Css.color(/* `hex */[
            5194459,
            Colors$ReactHooksTemplate.primary200
          ]),
      /* :: */[
        Css.fontSize(/* `px */[
              25096,
              24
            ]),
        /* :: */[
          Css.fontWeight(/* `num */[
                5496390,
                500
              ]),
          /* :: */[
            Css.lineHeight(/* `px */[
                  25096,
                  36
                ]),
            /* :: */[
              Css.marginBottom(/* `px */[
                    25096,
                    12
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var smallHeader = Css.style(/* :: */[
      Css.color(/* `hex */[
            5194459,
            Colors$ReactHooksTemplate.primary400
          ]),
      /* :: */[
        Css.fontSize(/* `px */[
              25096,
              9
            ]),
        /* :: */[
          Css.lineHeight(/* `px */[
                25096,
                11
              ]),
          /* :: */[
            Css.marginBottom(/* `px */[
                  25096,
                  8
                ]),
            /* :: */[
              Css.textTransform(/* uppercase */-415330030),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[
  /* body */body,
  /* header */header,
  /* smallHeader */smallHeader
];

function Text$body(Props) {
  var children = Props.children;
  var className = Props.className;
  return React.createElement("div", {
              className: Cn.make(/* :: */[
                    body,
                    /* :: */[
                      Cn.unpack(className),
                      /* [] */0
                    ]
                  ])
            }, children);
}

function Text$header(Props) {
  var children = Props.children;
  var className = Props.className;
  return React.createElement("div", {
              className: Cn.make(/* :: */[
                    header,
                    /* :: */[
                      Cn.unpack(className),
                      /* [] */0
                    ]
                  ])
            }, children);
}

function Text$smallHeader(Props) {
  var children = Props.children;
  var className = Props.className;
  return React.createElement("div", {
              className: Cn.make(/* :: */[
                    smallHeader,
                    /* :: */[
                      Cn.unpack(className),
                      /* [] */0
                    ]
                  ])
            }, children);
}

var body$1 = Text$body;

var header$1 = Text$header;

var smallHeader$1 = Text$smallHeader;

exports.Styles = Styles;
exports.body = body$1;
exports.header = header$1;
exports.smallHeader = smallHeader$1;
/* body Not a pure module */
