// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Colors$ReactHooksTemplate = require("../components/theme/Colors.bs.js");
var ContextLayer$ReactHooksTemplate = require("../components/layer/ContextLayer.bs.js");

var contextLayer = Css.style(/* :: */[
      Css.backgroundColor(/* `hex */[
            5194459,
            Colors$ReactHooksTemplate.primary475
          ]),
      /* [] */0
    ]);

var Styles = /* module */[/* contextLayer */contextLayer];

function ContextLayerExample(Props) {
  var match = React.useState((function () {
          return false;
        }));
  var setShowLayer = match[1];
  var divRef = React.useRef(null);
  React.useEffect((function () {
          Curry._1(setShowLayer, (function (param) {
                  return true;
                }));
          return undefined;
        }), ([]));
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  ref: divRef
                }, "Context"), match[0] ? React.createElement(React.Fragment, undefined, React.createElement(ContextLayer$ReactHooksTemplate.make, {
                        contextRef: divRef,
                        position: /* Top */0,
                        children: (function (param) {
                            return React.createElement("div", {
                                        className: contextLayer
                                      }, "ContextLayer");
                          })
                      }), React.createElement(ContextLayer$ReactHooksTemplate.make, {
                        contextRef: divRef,
                        position: /* Bottom */1,
                        children: (function (param) {
                            return React.createElement("div", {
                                        className: contextLayer
                                      }, "ContextLayer");
                          })
                      }), React.createElement(ContextLayer$ReactHooksTemplate.make, {
                        contextRef: divRef,
                        position: /* Left */2,
                        children: (function (param) {
                            return React.createElement("div", {
                                        className: contextLayer
                                      }, "ContextLayer");
                          })
                      }), React.createElement(ContextLayer$ReactHooksTemplate.make, {
                        contextRef: divRef,
                        position: /* Right */3,
                        children: (function (param) {
                            return React.createElement("div", {
                                        className: contextLayer
                                      }, "ContextLayer");
                          })
                      })) : null);
}

var make = ContextLayerExample;

exports.Styles = Styles;
exports.make = make;
/* contextLayer Not a pure module */
