// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Grid$ReactHooksTemplate = require("../components/Grid.bs.js");
var Button$ReactHooksTemplate = require("../components/Button.bs.js");
var Select$ReactHooksTemplate = require("../components/inputs/Select.bs.js");
var Spacing$ReactHooksTemplate = require("../components/theme/Spacing.bs.js");
var TextInput$ReactHooksTemplate = require("../components/inputs/TextInput.bs.js");

var row = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.justifyContent(/* flexEnd */924268066),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* row */row];

var states = /* array */[
  "AK",
  "AL",
  "AR",
  "AZ",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "IA",
  "ID",
  "IL",
  "IN",
  "KS",
  "KY",
  "LA",
  "MA",
  "MD",
  "ME",
  "MI",
  "MN",
  "MO",
  "MS",
  "MT",
  "NC",
  "ND",
  "NE",
  "NH",
  "NJ",
  "NM",
  "NV",
  "NY",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VA",
  "VT",
  "WA",
  "WI",
  "WV",
  "WY"
];

var stateOptions = states.map((function (state) {
        return /* record */[/* label */state];
      }));

function getStateOptions(_value) {
  return stateOptions.slice(0, 8);
}

function FormExample(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var setState = match[1];
  var onStateChange = React.useCallback((function (option) {
          return Curry._1(setState, (function (param) {
                        return option;
                      }));
        }), ([]));
  return React.createElement("div", undefined, React.createElement("div", {
                  className: Spacing$ReactHooksTemplate.marginBottom16
                }, React.createElement(TextInput$ReactHooksTemplate.make, {
                      label: "Street Address",
                      placeholder: "1 Folsom Street"
                    })), React.createElement(Grid$ReactHooksTemplate.row, {
                  className: Spacing$ReactHooksTemplate.marginBottom16,
                  children: null
                }, React.createElement(Grid$ReactHooksTemplate.cell, {
                      span: 6,
                      children: React.createElement(TextInput$ReactHooksTemplate.make, {
                            label: "City",
                            placeholder: "San Francisco"
                          })
                    }), React.createElement(Grid$ReactHooksTemplate.cell, {
                      span: 6,
                      children: React.createElement(Select$ReactHooksTemplate.make, {
                            getOptions: getStateOptions,
                            selectedOption: match[0],
                            onChange: onStateChange,
                            label: "State",
                            placeholder: "CA",
                            withTextInput: false,
                            forceOption: true
                          })
                    })), React.createElement("div", {
                  className: row
                }, React.createElement(Button$ReactHooksTemplate.make, {
                      type_: /* Secondary */1,
                      children: "Save"
                    })));
}

var make = FormExample;

exports.Styles = Styles;
exports.states = states;
exports.stateOptions = stateOptions;
exports.getStateOptions = getStateOptions;
exports.make = make;
/* row Not a pure module */
