// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var primary100 = "202020";

var primary200 = "404040";

var primary300 = "808080";

var primary400 = "c0c0c0";

var primary450 = "e0e0e0";

var primary475 = "f0f0f0";

var primary490 = "f8f8f8";

var primary500 = "ffffff";

var pink = "fce6da";

exports.primary100 = primary100;
exports.primary200 = primary200;
exports.primary300 = primary300;
exports.primary400 = primary400;
exports.primary450 = primary450;
exports.primary475 = primary475;
exports.primary490 = primary490;
exports.primary500 = primary500;
exports.pink = pink;
/* No side effect */
