// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var marginBottom8 = Css.style(/* :: */[
      Css.marginBottom(/* `px */[
            25096,
            8
          ]),
      /* [] */0
    ]);

var marginBottom16 = Css.style(/* :: */[
      Css.marginBottom(/* `px */[
            25096,
            16
          ]),
      /* [] */0
    ]);

exports.marginBottom8 = marginBottom8;
exports.marginBottom16 = marginBottom16;
/* marginBottom8 Not a pure module */
